apiVersion: v1
kind: Pod
metadata:
  name: nginx-1
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1 
        preference:
          matchExpressions:
          - key: distype
            operator: Exists
  containers:
  - name: nginx-1
    image: nginx
    imagePullPolicy: IfNotPresent
