apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: learner-sign
spec:
  request: <your-certificate-request>
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 604800
  usages:
  - client auth
