apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: probe-1
  name: probe-1
spec:
  containers:
  - image: registry.k8s.io/busybox
    name: probe-1
    resources: {}
    command: 
      - /bin/sh
      - -c
      - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command: 
        -  cat
        -  /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
