apiVersion: v1
kind: Pod
metadata:
  name: env-single-secret
spec:
  containers:
  - name: envars-test-container
    image: nginx
    env:
    - name: FIRSTNAME
      valueFrom:
        secretKeyRef:
          name: secrets1
          key: FIRSTNAME
