apiVersion: v1
kind: Pod
metadata:
  name: multi-init
spec:
    containers:
     - name: my-app-container
       image: busybox
       command: ['sh','-c','echo App is running! && sleep 3600']
       env:
        - name: FIRSTNAME
          value: "nileena"
    initContainers:
    - name: my-init-container
      image: busybox
      command: ['sh','-c']
      args: ['until nslookup nil-service.nil.svc.cluster.local;do echo Still looking for the service!;sleep 2;done']
    - name: my-init-container-2
      image: busybox
      command: ['sh','-c']
      args: ['until nslookup nil-service2.nil2.svc.cluster.local;do echo Still looking for the service!;sleep 2;done']


